#top
site_top:
  path: /
  defaults: { _controller: 'Shokai\Controller\MainController::indexAction' }
 
#auth
login:
  path: /login
  defaults: { _controller: 'Shokai\Controller\AuthController::loginAction' }

login_callback:
  path: /login/callback
  defaults: { _controller: 'Shokai\Controller\AuthController::loginCallbackAction' }

logout:
  path: /logout
  defaults: { _controller: 'Shokai\Controller\AuthController::logoutAction' }

#friends
friends_list:
  path: /friends/list
  defaults: { _controller: 'Shokai\Controller\FriendsController::listAction' }